server:
  port: 7007
spring:
  application:
    name: config-${server.port}
  cloud:
    config:
      server:
        git:
          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/yangyiman/github-comfig.git
          #search-paths:
          # -
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: config-${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"