server:
  port: 7004
spring:
  application:
    name: consumer-${server.port}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka
  instance:
    hostname: zzzz
    prefer-ip-address: true