server:
  port: 7001
spring:
  application:
    name: eureka-server-${server.port}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7000/eureka/
