server:
  port: 7003
spring:
  application:
    name: provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka


  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: provider-7003
